version: "3.8"

services:
  app:
    build:
      context: ./containers/node
      dockerfile: DockerfileApp
    container_name: "${COMPOSE_PROJECT_NAME}_app"
    ports:
      - '5000:5000'
    volumes:
      - ./backend/:/app
    restart: always
    networks:
      - net
  client:
    build:
      context: ./containers/node
      dockerfile: DockerfileClient
    container_name: "${COMPOSE_PROJECT_NAME}_client"
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    volumes:
      - ./front/:/client/
    restart: always
    networks:
      - net


networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
    ipam:
      config:
        - subnet: 173.20.0.0/16