version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: containers/nodejs/DockerfileApp
    container_name: "tagging_tool_app"
    ports:
      - '5000:5000'
    volumes:
      - ./backend/:/src/app
      - /src/app/node_modules
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - net


  client:
    build:
      context: ./
      dockerfile: containers/nodejs/DockerfileClient
    container_name: "tagging_tool_client"
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    volumes:
      - ./front/:/src/client
      - /src/client/node_modules
    restart: always
    networks:
      - net
    depends_on:
      - app


networks:
  net:
    driver: bridge
#    driver_opts:
#      com.docker.network.driver.mtu: 1400
#    ipam:
#      config:
#        - subnet: 173.20.0.0/16